<!-- 组合小车底盘与摄像头 -->
<robot name="my_car_camera" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:include filename="$(find urdf_learning)/urdf/main.xacro"/>
    <xacro:include filename="$(find urdf_learning)/urdf/move.xacro"/>
    <xacro:include filename="$(find urdf_learning)/urdf/rplidar.xacro"/>
    <joint name="rplidar_joint" type="fixed">
        <origin xyz="0 0 ${0.07+wheel_height/2}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="laser_link"/>
    </joint>
</robot>
